<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // docs/bike_diagnosis_questionnaire.xlsx code 5313088969
        DB::table('bf_questions')->insert([
            ['id' => 1, 'section' => '体格', 'body' => '身長のレンジを選んでください', 'answer_type' => 'single'],
            ['id' => 2, 'section' => '体格', 'body' => '体重のレンジを選んでください', 'answer_type' => 'single'],
            ['id' => 3, 'section' => '体格', 'body' => '足つき性（足がべったり着くこと）の重視度', 'answer_type' => 'single'],
            ['id' => 4, 'section' => '経験', 'body' => 'バイクの運転経験年数', 'answer_type' => 'single'],
            ['id' => 5, 'section' => '用途', 'body' => '主な用途（最も近いもの1つ）', 'answer_type' => 'single'],
            ['id' => 6, 'section' => '環境', 'body' => '主な走行環境（最も近いもの1つ）', 'answer_type' => 'single'],
            ['id' => 7, 'section' => '嗜好', 'body' => '取り回しの軽さ重視度', 'answer_type' => 'single'],
            ['id' => 8, 'section' => '嗜好', 'body' => 'デザイン志向に最も近いもの', 'answer_type' => 'single'],
            ['id' => 9, 'section' => 'コスト', 'body' => '維持費の重視度', 'answer_type' => 'single'],
            ['id' => 10, 'section' => '快適', 'body' => '積載・快適性の重視度', 'answer_type' => 'single'],
            ['id' => 11, 'section' => '制約', 'body' => '購入予算（万円）', 'answer_type' => 'single'],
            ['id' => 12, 'section' => '免許', 'body' => '現在の二輪免許区分', 'answer_type' => 'single'],
        ]);
        // End of docs/bike_diagnosis_questionnaire.xlsx code 5313088969


// docs/bike_diagnosis_questionnaire.xlsx code 1646515591
        DB::table('bf_options')->insert([
            ['sno' => '1', 'question_id' => 1, 'label' => '<160cm',],
            ['sno' => '2', 'question_id' => 1, 'label' => '160-170cm',],
            ['sno' => '3', 'question_id' => 1, 'label' => '170-180cm',],
            ['sno' => '4', 'question_id' => 1, 'label' => '>180cm',],
            ['sno' => '1', 'question_id' => 2, 'label' => '<55kg',],
            ['sno' => '2', 'question_id' => 2, 'label' => '55-70kg',],
            ['sno' => '3', 'question_id' => 2, 'label' => '70-85kg',],
            ['sno' => '4', 'question_id' => 2, 'label' => '>85kg',],
            ['sno' => '1', 'question_id' => 3, 'label' => '気にしない',],
            ['sno' => '2', 'question_id' => 3, 'label' => 'やや気にする',],
            ['sno' => '3', 'question_id' => 3, 'label' => 'かなり気にする',],
            ['sno' => '1', 'question_id' => 4, 'label' => 'なし',],
            ['sno' => '2', 'question_id' => 4, 'label' => '教習中',],
            ['sno' => '3', 'question_id' => 4, 'label' => '1年未満',],
            ['sno' => '4', 'question_id' => 4, 'label' => '1-3年',],
            ['sno' => '5', 'question_id' => 4, 'label' => '3年以上',],
            ['sno' => '1', 'question_id' => 5, 'label' => '通勤通学',],
            ['sno' => '2', 'question_id' => 5, 'label' => '街乗り',],
            ['sno' => '3', 'question_id' => 5, 'label' => '週末ツーリング',],
            ['sno' => '4', 'question_id' => 5, 'label' => '長距離ツアラー',],
            ['sno' => '5', 'question_id' => 5, 'label' => 'オフロード',],
            ['sno' => '6', 'question_id' => 5, 'label' => 'サーキット/峠',],
            ['sno' => '7', 'question_id' => 5, 'label' => '二人乗りが多い',],
            ['sno' => '8', 'question_id' => 5, 'label' => '買い物・積載重視',],
            ['sno' => '1', 'question_id' => 6, 'label' => '都市部',],
            ['sno' => '2', 'question_id' => 6, 'label' => '郊外',],
            ['sno' => '3', 'question_id' => 6, 'label' => '山間部',],
            ['sno' => '4', 'question_id' => 6, 'label' => '高速道路が多い',],
            ['sno' => '5', 'question_id' => 6, 'label' => '未舗装路が多い',],
            ['sno' => '1', 'question_id' => 7, 'label' => '低',],
            ['sno' => '2', 'question_id' => 7, 'label' => '中',],
            ['sno' => '3', 'question_id' => 7, 'label' => '高',],
            ['sno' => '1', 'question_id' => 8, 'label' => 'クラシック',],
            ['sno' => '2', 'question_id' => 8, 'label' => 'ネオクラ',],
            ['sno' => '3', 'question_id' => 8, 'label' => 'スポーツ',],
            ['sno' => '4', 'question_id' => 8, 'label' => 'アドベンチャー',],
            ['sno' => '5', 'question_id' => 8, 'label' => 'アメリカン',],
            ['sno' => '6', 'question_id' => 8, 'label' => 'スクーター',],
            ['sno' => '1', 'question_id' => 9, 'label' => '低',],
            ['sno' => '2', 'question_id' => 9, 'label' => '中',],
            ['sno' => '3', 'question_id' => 9, 'label' => '高',],
            ['sno' => '1', 'question_id' => 10, 'label' => '低',],
            ['sno' => '2', 'question_id' => 10, 'label' => '中',],
            ['sno' => '3', 'question_id' => 10, 'label' => '高',],
            ['sno' => '1', 'question_id' => 11, 'label' => '<30',],
            ['sno' => '2', 'question_id' => 11, 'label' => '30-60',],
            ['sno' => '3', 'question_id' => 11, 'label' => '60-100',],
            ['sno' => '4', 'question_id' => 11, 'label' => '100-150',],
            ['sno' => '5', 'question_id' => 11, 'label' => '>150',],
            ['sno' => '1', 'question_id' => 12, 'label' => '原付',],
            ['sno' => '2', 'question_id' => 12, 'label' => '小型限定',],
            ['sno' => '3', 'question_id' => 12, 'label' => '普通二輪',],
            ['sno' => '4', 'question_id' => 12, 'label' => '大型',],
        ]);
// End of docs/bike_diagnosis_questionnaire.xlsx code 1646515591

        // docs/bike_diagnosis_questionnaire.xlsx code 3993290321
        DB::table('bf_genres')->insert([
            ['id' => 1, 'name' => 'ネイキッド',],
            ['id' => 2, 'name' => 'スーパースポーツ',],
            ['id' => 3, 'name' => 'レーサーレプリカ',],
            ['id' => 4, 'name' => 'オフロード',],
            ['id' => 5, 'name' => 'モタード',],
            ['id' => 6, 'name' => 'ストリートファイター',],
            ['id' => 7, 'name' => 'クルーザー',],
            ['id' => 8, 'name' => 'ツアラー',],
            ['id' => 9, 'name' => 'カフェレーサー',],
            ['id' => 10, 'name' => 'スクランブラー',],
            ['id' => 11, 'name' => 'アドベンチャー',],
            ['id' => 12, 'name' => 'クラシック',],
            ['id' => 13, 'name' => 'ネオクラシック',],
            ['id' => 14, 'name' => 'スクーター',],
            ['id' => 15, 'name' => 'ミニバイク',],
        ]);
        // End of docs/bike_diagnosis_questionnaire.xlsx code 3993290321


// docs/bike_diagnosis_questionnaire.xlsx code 3230580247
        DB::table('bf_weights')->insert([
            ['question_id' => 1, 'option_id' => '1', 'genre_id' => '1', 'score' => '5'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '2', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '7', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '8', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '11', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '12', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '14', 'score' => '5'], ['question_id' => 1, 'option_id' => '1', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 1, 'option_id' => '2', 'genre_id' => '1', 'score' => '4'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '9', 'score' => '0'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '10', 'score' => '0'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '11', 'score' => '0'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '12', 'score' => '4'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '13', 'score' => '4'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '14', 'score' => '4'], ['question_id' => 1, 'option_id' => '2', 'genre_id' => '15', 'score' => '4'],
            ['question_id' => 1, 'option_id' => '3', 'genre_id' => '1', 'score' => '0'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '2', 'score' => '4'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '3', 'score' => '0'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '6', 'score' => '4'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '7', 'score' => '4'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '8', 'score' => '4'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '9', 'score' => '0'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '10', 'score' => '0'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '11', 'score' => '4'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '12', 'score' => '0'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '13', 'score' => '0'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '14', 'score' => '0'], ['question_id' => 1, 'option_id' => '3', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 1, 'option_id' => '4', 'genre_id' => '1', 'score' => '0'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '2', 'score' => '4'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '3', 'score' => '0'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '4', 'score' => '0'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '5', 'score' => '0'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '6', 'score' => '4'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '7', 'score' => '4'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '8', 'score' => '4'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '9', 'score' => '0'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '10', 'score' => '0'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '11', 'score' => '4'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '12', 'score' => '0'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '13', 'score' => '0'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '14', 'score' => '0'], ['question_id' => 1, 'option_id' => '4', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 2, 'option_id' => '1', 'genre_id' => '1', 'score' => '5'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '2', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '7', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '8', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '11', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '12', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '14', 'score' => '5'], ['question_id' => 2, 'option_id' => '1', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 2, 'option_id' => '2', 'genre_id' => '1', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '9', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '10', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '11', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '12', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '13', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '14', 'score' => '0'], ['question_id' => 2, 'option_id' => '2', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 2, 'option_id' => '3', 'genre_id' => '1', 'score' => '0'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '2', 'score' => '0'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '3', 'score' => '0'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '6', 'score' => '0'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '7', 'score' => '4'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '8', 'score' => '4'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '9', 'score' => '0'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '10', 'score' => '0'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '11', 'score' => '4'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '12', 'score' => '0'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '13', 'score' => '0'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '14', 'score' => '0'], ['question_id' => 2, 'option_id' => '3', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 2, 'option_id' => '4', 'genre_id' => '1', 'score' => '0'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '2', 'score' => '0'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '3', 'score' => '0'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '4', 'score' => '0'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '5', 'score' => '0'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '6', 'score' => '0'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '7', 'score' => '4'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '8', 'score' => '4'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '9', 'score' => '0'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '10', 'score' => '0'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '11', 'score' => '4'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '12', 'score' => '0'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '13', 'score' => '0'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '14', 'score' => '0'], ['question_id' => 2, 'option_id' => '4', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 3, 'option_id' => '1', 'genre_id' => '1', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '2', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '7', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '8', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '11', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '12', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '14', 'score' => '0'], ['question_id' => 3, 'option_id' => '1', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 3, 'option_id' => '2', 'genre_id' => '1', 'score' => '3'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '9', 'score' => '0'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '10', 'score' => '0'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '11', 'score' => '0'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '12', 'score' => '3'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '13', 'score' => '3'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '14', 'score' => '0'], ['question_id' => 3, 'option_id' => '2', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 3, 'option_id' => '3', 'genre_id' => '1', 'score' => '5'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '2', 'score' => '0'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '3', 'score' => '0'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '6', 'score' => '0'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '7', 'score' => '5'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '8', 'score' => '0'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '9', 'score' => '0'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '10', 'score' => '0'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '11', 'score' => '0'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '12', 'score' => '0'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '13', 'score' => '0'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '14', 'score' => '5'], ['question_id' => 3, 'option_id' => '3', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 4, 'option_id' => '1', 'genre_id' => '1', 'score' => '5'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '2', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '7', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '8', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '11', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '12', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '14', 'score' => '5'], ['question_id' => 4, 'option_id' => '1', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 4, 'option_id' => '2', 'genre_id' => '1', 'score' => '5'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '9', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '10', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '11', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '12', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '13', 'score' => '0'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '14', 'score' => '5'], ['question_id' => 4, 'option_id' => '2', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 4, 'option_id' => '3', 'genre_id' => '1', 'score' => '5'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '2', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '3', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '6', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '7', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '8', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '9', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '10', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '11', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '12', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '13', 'score' => '0'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '14', 'score' => '5'], ['question_id' => 4, 'option_id' => '3', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 4, 'option_id' => '4', 'genre_id' => '1', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '2', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '3', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '4', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '5', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '6', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '7', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '8', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '9', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '10', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '11', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '12', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '13', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '14', 'score' => '0'], ['question_id' => 4, 'option_id' => '4', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 4, 'option_id' => '5', 'genre_id' => '1', 'score' => '0'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '2', 'score' => '4'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '3', 'score' => '4'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '4', 'score' => '4'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '5', 'score' => '0'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '6', 'score' => '4'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '7', 'score' => '0'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '8', 'score' => '0'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '9', 'score' => '0'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '10', 'score' => '0'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '11', 'score' => '4'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '12', 'score' => '0'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '13', 'score' => '0'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '14', 'score' => '0'], ['question_id' => 4, 'option_id' => '5', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 5, 'option_id' => '1', 'genre_id' => '1', 'score' => '5'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '2', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '7', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '8', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '11', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '12', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '14', 'score' => '5'], ['question_id' => 5, 'option_id' => '1', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 5, 'option_id' => '2', 'genre_id' => '1', 'score' => '4'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '9', 'score' => '4'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '10', 'score' => '4'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '11', 'score' => '0'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '12', 'score' => '4'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '13', 'score' => '4'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '14', 'score' => '0'], ['question_id' => 5, 'option_id' => '2', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 5, 'option_id' => '3', 'genre_id' => '1', 'score' => '0'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '2', 'score' => '0'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '3', 'score' => '0'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '6', 'score' => '0'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '7', 'score' => '5'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '8', 'score' => '5'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '9', 'score' => '0'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '10', 'score' => '0'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '11', 'score' => '5'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '12', 'score' => '0'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '13', 'score' => '0'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '14', 'score' => '0'], ['question_id' => 5, 'option_id' => '3', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 5, 'option_id' => '4', 'genre_id' => '1', 'score' => '0'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '2', 'score' => '0'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '3', 'score' => '0'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '4', 'score' => '0'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '5', 'score' => '0'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '6', 'score' => '0'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '7', 'score' => '5'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '8', 'score' => '5'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '9', 'score' => '0'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '10', 'score' => '0'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '11', 'score' => '5'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '12', 'score' => '0'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '13', 'score' => '0'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '14', 'score' => '0'], ['question_id' => 5, 'option_id' => '4', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 5, 'option_id' => '5', 'genre_id' => '1', 'score' => '0'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '2', 'score' => '0'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '3', 'score' => '0'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '4', 'score' => '5'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '5', 'score' => '5'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '6', 'score' => '0'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '7', 'score' => '0'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '8', 'score' => '0'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '9', 'score' => '0'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '10', 'score' => '0'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '11', 'score' => '5'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '12', 'score' => '0'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '13', 'score' => '0'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '14', 'score' => '0'], ['question_id' => 5, 'option_id' => '5', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 5, 'option_id' => '6', 'genre_id' => '1', 'score' => '0'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '2', 'score' => '5'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '3', 'score' => '5'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '4', 'score' => '0'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '5', 'score' => '5'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '6', 'score' => '5'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '7', 'score' => '0'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '8', 'score' => '0'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '9', 'score' => '0'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '10', 'score' => '0'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '11', 'score' => '0'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '12', 'score' => '0'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '13', 'score' => '0'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '14', 'score' => '0'], ['question_id' => 5, 'option_id' => '6', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 5, 'option_id' => '7', 'genre_id' => '1', 'score' => '0'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '2', 'score' => '0'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '3', 'score' => '0'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '4', 'score' => '0'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '5', 'score' => '0'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '6', 'score' => '0'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '7', 'score' => '5'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '8', 'score' => '5'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '9', 'score' => '0'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '10', 'score' => '0'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '11', 'score' => '0'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '12', 'score' => '0'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '13', 'score' => '0'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '14', 'score' => '5'], ['question_id' => 5, 'option_id' => '7', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 5, 'option_id' => '8', 'genre_id' => '1', 'score' => '5'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '2', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '3', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '4', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '5', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '6', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '7', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '8', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '9', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '10', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '11', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '12', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '13', 'score' => '0'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '14', 'score' => '5'], ['question_id' => 5, 'option_id' => '8', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 6, 'option_id' => '1', 'genre_id' => '1', 'score' => '5'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '2', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '7', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '8', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '11', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '12', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '14', 'score' => '5'], ['question_id' => 6, 'option_id' => '1', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 6, 'option_id' => '2', 'genre_id' => '1', 'score' => '4'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '9', 'score' => '4'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '10', 'score' => '4'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '11', 'score' => '4'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '12', 'score' => '0'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '13', 'score' => '0'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '14', 'score' => '0'], ['question_id' => 6, 'option_id' => '2', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 6, 'option_id' => '3', 'genre_id' => '1', 'score' => '4'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '2', 'score' => '0'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '3', 'score' => '0'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '6', 'score' => '0'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '7', 'score' => '0'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '8', 'score' => '0'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '9', 'score' => '4'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '10', 'score' => '4'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '11', 'score' => '4'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '12', 'score' => '0'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '13', 'score' => '0'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '14', 'score' => '0'], ['question_id' => 6, 'option_id' => '3', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 6, 'option_id' => '4', 'genre_id' => '1', 'score' => '0'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '2', 'score' => '0'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '3', 'score' => '0'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '4', 'score' => '0'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '5', 'score' => '0'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '6', 'score' => '0'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '7', 'score' => '5'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '8', 'score' => '5'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '9', 'score' => '0'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '10', 'score' => '0'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '11', 'score' => '5'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '12', 'score' => '0'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '13', 'score' => '0'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '14', 'score' => '0'], ['question_id' => 6, 'option_id' => '4', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 6, 'option_id' => '5', 'genre_id' => '1', 'score' => '0'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '2', 'score' => '0'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '3', 'score' => '0'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '4', 'score' => '5'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '5', 'score' => '5'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '6', 'score' => '0'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '7', 'score' => '0'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '8', 'score' => '0'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '9', 'score' => '0'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '10', 'score' => '5'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '11', 'score' => '5'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '12', 'score' => '0'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '13', 'score' => '0'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '14', 'score' => '0'], ['question_id' => 6, 'option_id' => '5', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 7, 'option_id' => '1', 'genre_id' => '1', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '2', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '7', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '8', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '11', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '12', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '14', 'score' => '0'], ['question_id' => 7, 'option_id' => '1', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 7, 'option_id' => '2', 'genre_id' => '1', 'score' => '0'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '9', 'score' => '3'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '10', 'score' => '0'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '11', 'score' => '0'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '12', 'score' => '3'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '13', 'score' => '3'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '14', 'score' => '0'], ['question_id' => 7, 'option_id' => '2', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 7, 'option_id' => '3', 'genre_id' => '1', 'score' => '5'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '2', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '3', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '6', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '7', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '8', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '9', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '10', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '11', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '12', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '13', 'score' => '0'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '14', 'score' => '5'], ['question_id' => 7, 'option_id' => '3', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 8, 'option_id' => '1', 'genre_id' => '1', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '2', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '7', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '8', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '11', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '12', 'score' => '5'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '14', 'score' => '0'], ['question_id' => 8, 'option_id' => '1', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 8, 'option_id' => '2', 'genre_id' => '1', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '9', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '10', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '11', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '12', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '13', 'score' => '5'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '14', 'score' => '0'], ['question_id' => 8, 'option_id' => '2', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 8, 'option_id' => '3', 'genre_id' => '1', 'score' => '0'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '2', 'score' => '5'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '3', 'score' => '5'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '6', 'score' => '5'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '7', 'score' => '0'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '8', 'score' => '0'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '9', 'score' => '0'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '10', 'score' => '0'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '11', 'score' => '0'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '12', 'score' => '0'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '13', 'score' => '0'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '14', 'score' => '0'], ['question_id' => 8, 'option_id' => '3', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 8, 'option_id' => '4', 'genre_id' => '1', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '2', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '3', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '4', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '5', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '6', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '7', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '8', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '9', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '10', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '11', 'score' => '5'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '12', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '13', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '14', 'score' => '0'], ['question_id' => 8, 'option_id' => '4', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 8, 'option_id' => '5', 'genre_id' => '1', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '2', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '3', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '4', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '5', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '6', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '7', 'score' => '5'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '8', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '9', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '10', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '11', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '12', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '13', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '14', 'score' => '0'], ['question_id' => 8, 'option_id' => '5', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 8, 'option_id' => '6', 'genre_id' => '1', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '2', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '3', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '4', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '5', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '6', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '7', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '8', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '9', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '10', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '11', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '12', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '13', 'score' => '0'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '14', 'score' => '5'], ['question_id' => 8, 'option_id' => '6', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 9, 'option_id' => '1', 'genre_id' => '1', 'score' => '0'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '2', 'score' => '3'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '7', 'score' => '3'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '8', 'score' => '3'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '11', 'score' => '3'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '12', 'score' => '0'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '14', 'score' => '0'], ['question_id' => 9, 'option_id' => '1', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 9, 'option_id' => '2', 'genre_id' => '1', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '9', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '10', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '11', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '12', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '13', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '14', 'score' => '0'], ['question_id' => 9, 'option_id' => '2', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 9, 'option_id' => '3', 'genre_id' => '1', 'score' => '5'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '2', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '3', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '6', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '7', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '8', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '9', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '10', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '11', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '12', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '13', 'score' => '0'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '14', 'score' => '5'], ['question_id' => 9, 'option_id' => '3', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 10, 'option_id' => '1', 'genre_id' => '1', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '2', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '7', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '8', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '11', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '12', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '14', 'score' => '0'], ['question_id' => 10, 'option_id' => '1', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 10, 'option_id' => '2', 'genre_id' => '1', 'score' => '3'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '9', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '10', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '11', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '12', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '13', 'score' => '3'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '14', 'score' => '0'], ['question_id' => 10, 'option_id' => '2', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 10, 'option_id' => '3', 'genre_id' => '1', 'score' => '0'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '2', 'score' => '0'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '3', 'score' => '0'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '6', 'score' => '0'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '7', 'score' => '5'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '8', 'score' => '5'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '9', 'score' => '0'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '10', 'score' => '0'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '11', 'score' => '5'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '12', 'score' => '0'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '13', 'score' => '0'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '14', 'score' => '5'], ['question_id' => 10, 'option_id' => '3', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 11, 'option_id' => '1', 'genre_id' => '1', 'score' => '5'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '2', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '7', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '8', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '11', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '12', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '14', 'score' => '5'], ['question_id' => 11, 'option_id' => '1', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 11, 'option_id' => '2', 'genre_id' => '1', 'score' => '5'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '9', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '10', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '11', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '12', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '13', 'score' => '0'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '14', 'score' => '5'], ['question_id' => 11, 'option_id' => '2', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 11, 'option_id' => '3', 'genre_id' => '1', 'score' => '3'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '2', 'score' => '0'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '3', 'score' => '0'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '6', 'score' => '0'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '7', 'score' => '0'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '8', 'score' => '0'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '9', 'score' => '0'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '10', 'score' => '0'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '11', 'score' => '3'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '12', 'score' => '3'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '13', 'score' => '3'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '14', 'score' => '0'], ['question_id' => 11, 'option_id' => '3', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 11, 'option_id' => '4', 'genre_id' => '1', 'score' => '3'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '2', 'score' => '0'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '3', 'score' => '0'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '4', 'score' => '0'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '5', 'score' => '0'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '6', 'score' => '0'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '7', 'score' => '0'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '8', 'score' => '0'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '9', 'score' => '0'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '10', 'score' => '0'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '11', 'score' => '3'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '12', 'score' => '3'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '13', 'score' => '3'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '14', 'score' => '0'], ['question_id' => 11, 'option_id' => '4', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 11, 'option_id' => '5', 'genre_id' => '1', 'score' => '0'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '2', 'score' => '4'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '3', 'score' => '0'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '4', 'score' => '0'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '5', 'score' => '0'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '6', 'score' => '0'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '7', 'score' => '4'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '8', 'score' => '4'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '9', 'score' => '0'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '10', 'score' => '0'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '11', 'score' => '4'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '12', 'score' => '0'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '13', 'score' => '0'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '14', 'score' => '0'], ['question_id' => 11, 'option_id' => '5', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 12, 'option_id' => '1', 'genre_id' => '1', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '2', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '3', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '4', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '5', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '6', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '7', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '8', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '9', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '10', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '11', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '12', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '13', 'score' => '0'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '14', 'score' => '5'], ['question_id' => 12, 'option_id' => '1', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 12, 'option_id' => '2', 'genre_id' => '1', 'score' => '5'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '2', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '3', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '4', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '5', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '6', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '7', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '8', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '9', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '10', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '11', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '12', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '13', 'score' => '0'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '14', 'score' => '5'], ['question_id' => 12, 'option_id' => '2', 'genre_id' => '15', 'score' => '5'],
            ['question_id' => 12, 'option_id' => '3', 'genre_id' => '1', 'score' => '4'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '2', 'score' => '0'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '3', 'score' => '0'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '4', 'score' => '0'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '5', 'score' => '0'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '6', 'score' => '0'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '7', 'score' => '0'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '8', 'score' => '0'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '9', 'score' => '0'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '10', 'score' => '0'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '11', 'score' => '4'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '12', 'score' => '4'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '13', 'score' => '4'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '14', 'score' => '0'], ['question_id' => 12, 'option_id' => '3', 'genre_id' => '15', 'score' => '0'],
            ['question_id' => 12, 'option_id' => '4', 'genre_id' => '1', 'score' => '0'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '2', 'score' => '5'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '3', 'score' => '0'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '4', 'score' => '0'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '5', 'score' => '0'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '6', 'score' => '0'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '7', 'score' => '5'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '8', 'score' => '5'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '9', 'score' => '0'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '10', 'score' => '0'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '11', 'score' => '5'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '12', 'score' => '0'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '13', 'score' => '0'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '14', 'score' => '0'], ['question_id' => 12, 'option_id' => '4', 'genre_id' => '15', 'score' => '0'],
        ]);
// End of docs/bike_diagnosis_questionnaire.xlsx code 3230580247


    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
    }
};
